INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('1','RIEVER','ALBION');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('2','','ATKINSON');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('3','FT85.400','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('4','FTGCF85.430','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('5','FTGCF85.430','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('6','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('7','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('8','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('9','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('10','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('11','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('12','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('13','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('14','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('15','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('16','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('17','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('18','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('19','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('20','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('21','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('22','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('23','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('24','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('25','FTGCF85.460E','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('26','FTGCF85.460V','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('27','FTGCF85.460V','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('28','FTGCF85.460V','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('29','FTGCF85.460V','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('30','FTGCF85.460V','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('31','FTGXF105.510','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('32','FTGCF85.460V','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('33','FTGCF85.460V','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('34','FTGCF85.460V','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('35','FTGXF105.510','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('36','FTGCF85.460V','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('37','FTGCF85.460V','DAF');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('38','P310 6x2','Scania');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('39','R620 6x2*4','Scania');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('40','P230 4x2','Scania');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('41','P230 4x2','Scania');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('42','P230 4x2','Scania');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('43','P230 4x2','Scania');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('44','R270 6x2','Scania');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('45','R270 6x2','Scania');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('46','R270 6x2','Scania');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('47','P94 4x2','Scania');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('48','TGM','MAN');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('49','M 2000','MAN');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('50','TGM','MAN');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('51','TGM','MAN');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('52','TGM','MAN');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('53','TGM','MAN');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('54','TGL','MAN');
INSERT INTO VEHICLE_TYPE(Vehicle_type_id,Model,Make) VALUES ('55','TGL','MAN');
